---
- hosts: jenkins-master
  become: yes
  tasks:
    - name: Add Jenkins repository key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins Official Repository
        baseurl: https://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        enabled: yes
        state: present

    - name: Install Java
      yum:
        name: java-11-openjdk
        state: present

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started

    - name: Enable Jenkins to start at boot time
      service:
        name: jenkins
        enabled: yes
