---
- hosts: jenkins-slave
  become: yes
  tasks:
    - name: Update CentOS repo and cache
      yum:
        name: '*'
        state: latest
      async: 3600
      poll: 0

    - name: Install Java
      yum:
        name: java-11-openjdk
        state: present

    - name: Download Maven packages
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
        dest: /opt

    - name: Extract Maven packages
      unarchive:
        src: /opt/apache-maven-3.9.5-bin.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Move Maven-* to maven
      command: mv /opt/apache-maven-3.9.5-bin.tar.gz /opt/maven